# Generated by Django 4.1.3 on 2023-06-07 04:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescripcion',
            fields=[
                ('idPrescripcion', models.AutoField(primary_key=True, serialize=False, verbose_name='Id prescripcion')),
                ('rutPaciente', models.CharField(max_length=10, verbose_name='Rut del paciente')),
                ('fecha', models.DateField(auto_now_add=True, verbose_name='Fecha de creacion de prescripcion')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado de la prescripcion')),
                ('medico', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Medico')),
            ],
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('idReceta', models.AutoField(primary_key=True, serialize=False, verbose_name='Id de la receta')),
                ('medicamento', models.CharField(max_length=30, verbose_name='Nombre del medicamento')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad del medicamento')),
                ('prescripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.prescripcion')),
            ],
        ),
    ]
